api/package-lock.json, api/package.json, api/src/handlers.js, api/src/queryHelpers.js, api/test/api.test.js
Partially fixes #15
Adding 2 additional test cases:
- Items endpoint with invalid params has status code 400 (with implementation ported over from v1 of the api)
- Invalid endpoint response has status code 404
Added https://www.npmjs.com/package/http-status-codes for response codes
=> #15 add v1 use cases to rest api

dgraph/sample/data.json, dgraph/sample/data.rdf, dgraph/sample/schema.gql
Fixes #14
Re-populated Amox example from [wiki](https://sussol.net/wiki/doku.php/msupply:planning:projects:universal_codes_v2) into sample data files.
- Added SnoMED CT and Drug Bank Url
- Added nested property to schema (the existing examples already had this, though it wasn't explicitly defined in schema)
- Align RDF with JSON
Possible next steps if all good with this schema:
- Add Paracetamol example to RDF
- More products
- More API test cases
- Add sample expected API results based on test data
=> #14 expand rest api test data

api/src/mappers.js
Fixes #25 
Found a few minor issues:
- request.params is null in function (changed to request.query)
- request.url is null in function (changed to request.raw.url)
- full url with query string wasn't matching key to access PARAMETERS object
- reduce function was returning strange results e.g.:
- items?invalid=data&test=moredata => { valid: [], invalid: { query: 'test' } } 
- Changed to filter on whitelist - simpler but not as fancy (could see what it was trying to do - for educational purposes may test it locally some more)
Happy to hear if any of the changes could be done better!
=> #25 Update mapper.js

api/src/mappers.js, dgraph/sample/data.json
Fixes #22 
The `query` property of `data` is the array, not `data` itself. 
Have tweaked the mapper to reflect this and cope with an empty array and an undefined `query` or `data`
=> #22 tidy up response mapper

api/src/handlers.js, api/src/mappers.js, api/src/queries.js, api/src/schemas.js, api/test/api.test.js, api/test/fixtures/api/index.js, api/test/fixtures/api/items.json, api/test/fixtures/data/index.js, api/test/fixtures/data/items.json, api/test/fixtures/graph/index.js, api/test/fixtures/graph/items.json, api/test/fixtures/index.js
Fixes #27,
Completes the testing template for the v1 API, including:
- Fixtures:
- Test data.
- Expected graph responses.
- Expected API responses.
- Additional `/items` tests, including examples of:
- Using fixtures for test data, expected responses etc.
- Simulating Dgraph responses with basic and bit more advanced `nock` functionality.
=> #27 add additional api test cases

.gitignore, dgraph/.gitignore, dgraph/graphql/src/api.js, dgraph/graphql/src/data.js, dgraph/graphql/src/resolvers.js, dgraph/graphql/src/schema.js, dgraph/package-lock.json, dgraph/package.json
Fixes #41 
- Applied following feedback from prior PR  
- Git Ignore: https://github.com/openmsupply/unified-codes/pull/55#discussion_r454751477
- Class Naming: https://github.com/openmsupply/unified-codes/pull/55#discussion_r454764168
- Class Constructor: https://github.com/openmsupply/unified-codes/pull/55#discussion_r454768144
-  New query added to schema (getDrugInteractions with universal code as input parameter)
- Custom resolver added to first query Dgraph for the RXCui, then query RxNav
**Future Improvements**
- Had some discussion with Craig and this sort of aligns with the previous demo on interactions, although it is now a GraphQL request/response rather than REST. Future improvement may be to structure this better (return properties rather than huge JSON string) and implement …
=> #41 add drug interaction lookup

unified-codes/apps/data-service/src/app/queries.ts, unified-codes/apps/data-service/src/app/resolvers.ts, unified-codes/apps/data-service/src/app/schema.ts, unified-codes/apps/data-service/src/app/utils.ts, unified-codes/apps/web/src/actions/ExplorerActions.ts, unified-codes/apps/web/src/components/templates/Explorer.stories.tsx, unified-codes/apps/web/src/components/templates/Explorer.tsx, unified-codes/apps/web/src/reducers/ExplorerReducer.ts, unified-codes/apps/web/src/sagas/ExplorerSaga.ts, unified-codes/apps/web/src/selectors/ExplorerSelectors.ts, unified-codes/apps/web/src/types/Store.ts, unified-codes/libs/data/src/lib/types/Entity.ts, unified-codes/libs/data/src/lib/types/Pagination.ts, unified-codes/libs/data/src/lib/types/index.ts, unified-codes/libs/ui/src/lib/components/entity/organisms/EntityBrowser.stories.tsx, unified-codes/libs/ui/src/lib/components/entity/organisms/EntityBrowser.tsx
Fixes #168 
Adds pagination support to the entity browser table. Each request is making a round trip back to the data-service. Ok for now, may change that later.
Started off using cursors and have ditched - this is much less code.
Am using the nomenclature from https://dgraph.io/tour/basic/9/ i.e. `first` and `offset` rather than `page` and `rowsPerPage`
Next steps:
- add in filter / search support
- add ordering of results
- remove hard coded max height ( this just helps me test, as all items are on the page! ) and fix up styles ( #152  )
1. Tests have been added to cover changes …
=> #168 add pagination to explorer

unified-codes/apps/data-service/src/app/queries.ts, unified-codes/apps/data-service/src/app/resolvers.ts, unified-codes/apps/data-service/src/app/schema.ts, unified-codes/apps/web/src/actions/ExplorerActions.ts, unified-codes/apps/web/src/components/templates/Explorer.stories.tsx, unified-codes/apps/web/src/components/templates/Explorer.tsx, unified-codes/apps/web/src/reducers/ExplorerReducer.ts, unified-codes/apps/web/src/sagas/ExplorerSaga.ts, unified-codes/apps/web/src/selectors/ExplorerSelectors.ts, unified-codes/apps/web/src/types/Store.ts, unified-codes/libs/data/src/lib/types/EntitySearch.ts, unified-codes/libs/data/src/lib/types/Explorer.ts, unified-codes/libs/data/src/lib/types/Pagination.ts, unified-codes/libs/data/src/lib/types/index.ts, unified-codes/libs/ui/src/lib/components/entity/organisms/EntityBrowser.tsx
Fixes #170 
This connects the `Explorer` filter function back to dgraph, using the regex syntax.
Ignore the pagination aspects, as that, I think, we'll move out of global state.
The use of a saga to run the search as a side-effect after updating the search parameters is potentially a bit iffy. It cleans up the code though, and I think there's an argument that if the search parameters are updated, then the search results should also be updated?
=> #170 add filter to explorer request

unified-codes/apps/data-service/src/app/queries.ts, unified-codes/apps/data-service/src/app/resolvers.ts, unified-codes/apps/data-service/src/app/schema.ts, unified-codes/apps/web/src/sagas/DetailSaga.ts
Fixes #219.
Small adjustment to GraphQL schema to match our internal `IEntity` type definition. This should make interactions and details work as expected again (and now only Dgraph/data-service should know about the naming `has_child` and `has_property`) 🥳  
Fields renamed:
- has_child -> children
- has_property -> properties 
New sample query format:
```
query GetProductByUC {
entity (code: "4231441c") {
code 
description
type
children {
code
description
type
children {
code
description
type
}
}
properties {
type
value
}
}
}
```
1. Tests have been added to cover changes introduced …
=> #219 Update GraphQL schema to match IEntity type

unified-codes/apps/web/src/components/containers/explorer/ExplorerPage.tsx, unified-codes/apps/web/src/components/containers/explorer/ExplorerProgressBar.tsx
Fixes #268 ( partly )
Add the ability to switch between progress indicators. Perhaps should have the sensible progress as the default and this as an easter egg?
Tidy up the backdrop when using the cat progress.
=> #268 add the ability to switch between progress indicators

unified-codes/apps/data-service/src/app/schema.ts, unified-codes/apps/data-service/src/app/types/DgraphDataSource.ts
Fixes #259 
Implement a `match` parameter on the `filter` property.
This optional value can be `exact | begins (default) | contains`
Can be tested using postman
```
{ "query": "{ entities(filter: { code: \"\" description: \"Dia\" type: \"[drug]\" match: \"contains\" }  offset: 0 first: 25) { data { code description type uid }, totalLength, }}"}
```
=> implement match filter element

unified-codes/apps/data-service/src/app/resolvers.ts, unified-codes/apps/data-service/src/app/schema.ts, unified-codes/apps/data-service/src/app/types/DgraphDataSource.ts, unified-codes/apps/data-service/src/app/types/RxNavDataSource.ts, unified-codes/libs/data/src/lib/types/DrugInteractions.ts, unified-codes/libs/data/src/lib/types/Entity.ts, unified-codes/libs/data/src/lib/types/index.ts
Fixes #281 and #231 
Add a new query for `interactions` and return errors as well as interactions in an array.
To test, poke this into Postman:
```
{ "query": " { interactions(code: \"46b9f43e\" severity: \"high\") { rxcui errors { message } data { name description severity rxcui} } } " }
```
A couple of example items are
- 46b9f43e which has an RxCUI assigned to the root product and is clinically depressed.. it has no highs only lows
- c24cdb96 - has no RxCUI assigned
=> #281 refactor interactions resolver

unified-codes/apps/web/src/components/containers/detail/DetailEntityList.tsx, unified-codes/apps/web/src/components/containers/detail/DetailEntityListItem.tsx
Fixes #387
- Expand entity tree by default to make it easier for users to see all available codes for a particular product.
- **Bold** the description and code for child-most items to make it clearer which items are able to be dispensed. 
- Not convinced it's super clear, but we couldn't really think of a better idea (icons would probably be even more confusing, and removing the copy icon for higher-level codes seems a bit mean since some people might want the higher codes for other use cases that aren't mSupply?)
- Ran prettier over the changed file (soz I probably just made it harder to review 😞 )  
Tick below if one of the …
=> #387 expand product tree by default

frontend/packages/common/src/api/GqlContext.tsx, frontend/packages/common/src/types/schema.ts, frontend/packages/host/src/Admin/Settings.tsx, frontend/packages/host/src/api/api.ts, frontend/packages/host/src/api/hooks/utils/useEntity.ts, frontend/packages/host/src/api/hooks/utils/useHostApi.ts, frontend/packages/host/src/api/operations.generated.ts, frontend/packages/host/src/api/operations.graphql, unified-codes/apps/data-loader/src/app/v2/DataLoader.ts, unified-codes/apps/data-service/src/app/main.ts, unified-codes/apps/data-service/src/app/v1/resolvers.ts, unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts, unified-codes/apps/data-service/src/app/v1/types/DgraphGqlDataSource.ts, unified-codes/apps/data-service/src/app/v1/types/queries/entityQuery.ts, unified-codes/data/v2/schema.gql, unified-codes/data/v2/schema.graphql, unified-codes/package.json, unified-codes/tools/scripts/dgraph/run.sh
- Updates local devving DGraph Docker image to v23
- Adds a GraphQL schema for Dgraph. There are a few changes related to moving to the GraphQL schema:
- While Dgraph queries are flexible enough to query across types, GraphQL queries are constrained to a particular type. However DGraph supports nodes having multiple types. 
- Updated the DataLoader to assign both a generic `Entity` type, as well as the more fine grained type (`Product`/`Route`/`Form` etc) - this allows us to use GraphQL to query the entities across any level of the hierarchy, or target a specific level
- Removes the `@lang` directive from the `name` predicate - this isn't currently supported through the GraphQL schema (you're supposed to map to language specific fields e.g. `name_en`), but we aren't storing any …
=> Graphql dgraph

unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts, unified-codes/apps/data-service/src/app/v1/types/DgraphGqlDataSource.ts
If query for entity has no result for whatever reason, we weren't checking for its existence before pulling children off it...
Adds a check and early return if `!entity` :)
=> Fix error when querying non-existent entity

backend/graphql/Cargo.toml, backend/graphql/lib.rs, backend/graphql_v1/universal_codes/src/types/drug_interaction.rs
Fixes #459 
Universal Codes `entities` and `entity` endpoint are now available under the `/graphql` path
=> Expose universal codes v1 under the main graphql endpoint

backend/dgraph/src/entity.rs, backend/dgraph/src/lib.rs, data-loader/data/v2/schema.graphql, data-loader/src/v2/DataLoader.ts
Fixes #468 
All nodes in the Universal Codes DB are now either `Entity` or `Property` types.
Updated queries in rust to maintain compatiblity, dataservice may well be broken now, haven't checked..
=> 468 refactor dgraph to remove extra types

frontend/host/src/Site.tsx, frontend/system/src/Admin/Service.tsx
Fixes #477
Redirects users away from `/admin/{something-unknown}` paths back to `/browse`, rather than showing the 404 page. This is due to the fact that the breadcrumbs are clickable, but don't actually direct the user to an existent page. Clicking a link within the app and getting taken to a 404 always has the feel of something being broken, so this seemed like the easiest next best thing.
Also moves the Paper/Box wrapper so the 404 page doesn't render within it - that looked weird... this is the before:
=> 477 fix links and redirects

backend/graphql/universal_codes/src/mutations/upsert.rs, backend/service/src/universal_codes/mod.rs, backend/service/src/universal_codes/tests/upsert.rs, backend/service/src/universal_codes/upsert.rs
Fixes #487 
Because the dgraph graphql library requires async functions, we weren't able t pass our normal `context` object around (with the storage connection it's not threadsafe)
To avoid this problem, I'm passing the user_id an service provider, then we can create connection in the function which needs to write to the audit log.
The storage connection is to allow functions to inherit database transactions for subsequent function calls.
Since we're not actually creating a transaction here, it's no needed.
Might be nice to create a new context struct though?
=> 487 audit logging for new or update codes

frontend/system/src/Entities/EntityDetails.tsx
Fixes #495
Switches from a Link component wrapper to using `navigate` on click. The Link component was taking on a full height, thus the clickable whitespace. We could have fixed this with CSS, but given the navigation is the result of the click, the navigate function seemed like the more appropriate option.
No longer clickable in the whitespace:
=> 495 fix clickable whitespace

frontend/system/src/Admin/EditDrug/DrugEditForm/DrugEditForm.tsx, frontend/system/src/Admin/EditDrug/DrugEditForm/VaccineEditForm.tsx
Fixes #506
Fixes #507
Adds a saving indicator while an entity is saving, this also avoids the issue with multiple button presses causing duplication.
=> 506 spamming the save button can result in duplicate records

backend/dgraph/Cargo.toml, backend/dgraph/src/client.rs, backend/dgraph/src/configuration/delete_configuration_item.rs, backend/dgraph/src/configuration/insert_configuration_item.rs, backend/dgraph/src/link_codes.rs, backend/dgraph/src/upsert_entity.rs
Fixes #510 
Uses a helper function with re-tries to avoid mutation conflicts when doing parallel updates/deletes.
`cargo test --features=dgraph-tests`
=> Use helper for dGraph retries

frontend/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx, frontend/system/src/Entities/EntitySearchBar.tsx
Comparison with Mui Autocomplete (well, our wrapper over it). Allows for use of arrow keys, and to keep typing in the input after you've used those arrow keys.
Could consider displaying more options than 3?
=> use mui autocomplete

frontend/host/src/RedirectDetails.tsx, frontend/host/src/Site.tsx
Fixes #483
Redirects `/details/:code` pages to `/browse/:code`, so links from the old web app will get redirected as expected in the new web app!
Test:
- Go to: http://localhost:4201/details/c7750265
- You should be redirected to http://localhost:4201/browse/c7750265 and see the Abacavir details
=> redirect old details route to new page

backend/dgraph/src/lib.rs, backend/dgraph/src/pending_change.rs, backend/dgraph/src/pending_changes.rs, backend/graphql/types/src/types/pending_change.rs, backend/graphql/universal_codes/src/types/inputs.rs, backend/service/src/universal_codes/add_pending_change.rs, backend/service/src/universal_codes/tests/add_pending_change.rs, backend/service/src/universal_codes/tests/reject_pending_change.rs, backend/service/src/universal_codes/tests/update_pending_change_body.rs, data-loader/data/v2/schema.graphql, frontend/common/src/types/schema.ts, frontend/system/src/Admin/EditEntity/ConsumableEditForm.tsx, frontend/system/src/Admin/EditEntity/DrugEditForm.tsx, frontend/system/src/Admin/EditEntity/VaccineEditForm.tsx, frontend/system/src/Admin/PendingChanges/ListView.tsx, frontend/system/src/Admin/api/operations.generated.ts, frontend/system/src/Admin/api/operations.graphql
Fixes #517
Removes the `requestedFor` field from pending changes:
Removes the property entirely, rather than just not displaying... this field was mostly to explain _why_ the change is being requested, which we'll only really need once external submissions are available, but something like a `reason` field will probably make more sense then.
=> 517 remove requested for

data-loader/data/v2/drugs.csv
Fixes #551 
Two products had the same product name but different codes, this seems to be the case all the way back to 4.3 version spreadsheets.
I've updated to use one (effectively deleting a code, but unlikely to be being used anywhere)
Wrote a quick python script to check for others product name code miss matches, but seems ok.
=> 551 duplicate names in dataloaded data

backend/graphql/configuration/src/lib.rs
Fixes #558 
Removes MutateUniversalCodes auth check on queries for property config items, so they are queryable when unauthenticated:
=> 558 allow querying property config items when unauthenticated

frontend/common/src/ui/components/buttons/standard/ButtonWithIcon.tsx
Fixes #565 
Moves the tooltip component inside the button component, so the button is still fully clickable even when the tooltip renders.
=> fix entity update button clickability

frontend/system/src/Entities/ListView.tsx
Fixes #446
Manages category filters as url query params so they persist on refresh/navigating back:
=> 446 store browsing categories in URL

backend/graphql_v1/universal_codes/src/types/entity_search_input.rs
Fixes #572 
Escapes slashes, searches now working as expected:
=> 572 escape slashes on entity search
