msupply-foundation/unified-codes

- README.md
- dgraph/alter.sh
- dgraph/docker.sh
- dgraph/mutate.sh
- dgraph/query.sh
Fixes #3.
Adds dgraph docker instructions to `README.md` and basic helper scripts.
> #3 add dgraph docker

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
Add templates for new issues and PRs.
> #37 add issue pr templates

- dgraph/docker.sh
Fixes #34.
Small 🐛 fix to allow me to startup docker on my windows machine.
> #34 update docker script for win compatibility

- api/src/mappers.js
- api/src/schemas.js
- dgraph/sample/data.json
Fixes #36.
Updates query parameters and mappers to comply with API expected by existing mSupply instances.
Note: tests to be added as part of existing WIP test PR (https://github.com/openmsupply/unified-codes/pull/28).
> #36 update api msupply compatibility

- .github/workflows/CI.yml
- api/package-lock.json
- api/package.json
- dgraph/docker.sh
Fixes #43.
Branches off #42.
Adds script for running existing tests with `nock` disabled.
> #43 add dgraph tests

- .github/workflows/CI.yml
Fixes #40.
Added workflow for automating jest tests.
API tests will be run for each PR, which should significantly speed up code reviews.
> #40 add jest continuous integration

- .github/workflows/CI.yml
- api/src/mappers.js
- api/src/queries.js
- api/test/api.test.js
- api/test/fixtures/api/items.json
- api/test/fixtures/data/items.json
- api/test/fixtures/graph/items.json
Fixes #45.
Branches off #44.
Fixes up bugs in API code and tests/fixtures which were causing failed graph tests.
> #45 fix failing graph tests

- web/.gitignore
- web/.storybook/main.js
- web/index.html
- web/package-lock.json
- web/package.json
- web/src/App.tsx
- web/src/index.tsx
- web/src/pages/HomePage.tsx
- web/stories/index.stories.tsx
- web/tsconfig.json
- web/webpack.config.js
Fixes #51.
Adds `web` project:
- `react`
- `typescript`
- `webpack`
- `storybook`
> #51 initialise web project

- dgraph/graphql/src/data.js
- dgraph/graphql/src/dgraph/queries.js
- dgraph/graphql/src/resolvers.js
- dgraph/graphql/src/schema.js
- dgraph/package-lock.json
- dgraph/package.json
Fixes #67 
- Replaced search by name query with query for all entities
- Added optional search filter (for type/code) - type will be necessary to retrieve non-medicinal products unless we add a parent 'products' node to our DB (which sits above medicinal_products and non medicinal products)
- Removed drug interactions query as per discussion - this will be added to the REST API (likely a low priority for Graph API as mSupply will query through REST). 
- NB: It may be tricky to know when and when not to request properties from the client side with this structure, as it is very generic - starting to possibly see the benefit of better typing! However this is just my observation...
**Sample queries (these will now need to be recursive):** 
- Generic request for all products and some …
> #67 update graph ql schema

- nx-workspace/apps/api/src/app/queries.ts
- nx-workspace/apps/api/test/api.test.js
Fixes #108. 
- Adjusted Dgraph query to first query for all unit_of_use nodes, then apply regex as filter (rather than using regex in top-level query). This seems to bypass Dgraph's Regex restrictions. Question also posted to Dgraph forum: https://discuss.dgraph.io/t/error-regular-expression-is-too-wide-ranging-and-can-t-be-executed-efficiently/9254 
- Test added for querying with a 2 char search term (just to validate that some results are returned - as there's already a test for the filtering)
2. This PR requires no …
> #108 product search failure with short term

- .gitignore
- nx-workspace/apps/auth-service/init-auth-service.sh
- nx-workspace/apps/data-service/src/app/server/schema.js
- nx-workspace/apps/web/.env
- nx-workspace/apps/web/src/App.tsx
- nx-workspace/apps/web/src/actions/MessageActions.ts
- nx-workspace/apps/web/src/actions/UserActions.ts
- nx-workspace/apps/web/src/actions/index.ts
- nx-workspace/apps/web/src/api.ts
- nx-workspace/apps/web/src/components/templates/Login.tsx
- nx-workspace/apps/web/src/reducers/MessageReducer.ts
- nx-workspace/apps/web/src/reducers/UserReducer.ts
- nx-workspace/apps/web/src/sagas/UserSagas.ts
- nx-workspace/apps/web/src/sagas/index.ts
- nx-workspace/apps/web/src/store.ts
- nx-workspace/apps/web/src/types/Authentication.ts
- nx-workspace/apps/web/src/types/Message.ts
- nx-workspace/apps/web/src/types/User.ts
- nx-workspace/apps/web/src/types/index.ts
- nx-workspace/apps/web/stories/EntityBrowser.stories.tsx
- nx-workspace/apps/web/stories/Explorer.stories.tsx
- nx-workspace/apps/web/stories/Login.stories.tsx
- nx-workspace/package-lock.json
- nx-workspace/package.json
Fixes #94 
Adds redux saga support and creates saga for user login
Also added .env entries - the `.local.env` is excluded from git and is useful for configuring your local environment.
> add redux saga support and wire up login

- unified-codes/apps/web/src/App.tsx
- unified-codes/apps/web/src/actions/AlertActions.ts
- unified-codes/apps/web/src/reducers/AlertReducer.ts
- unified-codes/apps/web/src/sagas/ExplorerSaga.ts
Fixes #142.
Branched off #140.
Sorry about the inception level branching, I figured this is the better option than potentially having to deal with messy merge conflicts!
Updates `AlertActions` identifies (no functionality changes).
> #142 update alert actions

- unified-codes/libs/ui/src/lib/components/entity/molecules/EntityTypeFilter.stories.tsx
Fixes #181.
Minor fix to get storybook UI running again. Removed incorrect theme import and added dummy types to EntityFilter story.
> #181 Fix NX Storybook UI

- unified-codes/apps/web/src/actions/DetailActions.ts
- unified-codes/apps/web/src/components/app/Footer.stories.tsx
- unified-codes/apps/web/src/components/detail/DetailViewer.tsx
- unified-codes/apps/web/src/components/explorer/ExplorerTableRows.tsx
- unified-codes/apps/web/src/reducers/DetailReducer.ts
- unified-codes/apps/web/src/sagas/DetailSaga.ts
- unified-codes/apps/web/src/sagas/index.ts
- unified-codes/apps/web/src/selectors/DetailSelectors.ts
- unified-codes/apps/web/src/types/Store.ts
Fixes #212.
Branched off #213.
Re-adds saga to fetch details in new code structure. NB: Details page currently loses the entity on refresh as it expects the entity to be set from the explorer - probably something to fix when re-visiting navigation..?
> #212 migrate entity details saga

- unified-codes/apps/web/src/actions/DetailActions.ts
- unified-codes/apps/web/src/actions/index.ts
- unified-codes/apps/web/src/components/app/App.tsx
- unified-codes/apps/web/src/components/app/Footer.stories.tsx
- unified-codes/apps/web/src/components/detail/DetailViewer.tsx
- unified-codes/apps/web/src/components/detail/index.ts
- unified-codes/apps/web/src/components/explorer/ExplorerBrowser.tsx
- unified-codes/apps/web/src/components/explorer/ExplorerTable.tsx
- unified-codes/apps/web/src/components/explorer/ExplorerTableRows.tsx
- unified-codes/apps/web/src/reducers/DetailReducer.ts
- unified-codes/apps/web/src/reducers/index.ts
- unified-codes/apps/web/src/sagas/DetailSaga.ts
- unified-codes/apps/web/src/sagas/index.ts
- unified-codes/apps/web/src/selectors/DetailSelectors.ts
- unified-codes/apps/web/src/selectors/index.ts
- unified-codes/apps/web/src/store/store.ts
- unified-codes/apps/web/src/types/Store.ts
- unified-codes/libs/data/src/lib/types/Entity.ts
- unified-codes/libs/data/src/lib/types/Property.ts
- unified-codes/libs/ui/src/lib/components/entity/molecules/EntityTable.tsx
- unified-codes/libs/ui/src/lib/components/entity/molecules/EntityTableRow.tsx
- unified-codes/libs/ui/src/lib/components/entity/molecules/EntityTableRows.tsx
Fixes #209.
Migrates details page to refactor branch.
Next steps are to complete the details page UI and add sagas for fetching entity data.
> #209 migrate details page

- unified-codes/apps/web/src/components/app/App.tsx
- unified-codes/apps/web/src/components/explorer/ExplorerBrowser.tsx
- unified-codes/apps/web/src/reducers/ExplorerReducer.ts
- unified-codes/apps/web/src/selectors/ExplorerSelectors.ts
- unified-codes/apps/web/src/styles/theme.ts
- unified-codes/apps/web/src/types/Theme.ts
- unified-codes/libs/ui/src/lib/components/entity/organisms/EntityBrowser.tsx
Fixes #229 
Adds a backdrop and circular progress loading indication ( thanks @katherine-sussol - this is all your work 😃  )
> add loading indicator

- unified-codes/apps/web/src/routes/routes.ts
Fixes #233 
Just a small one - removing the warnings of circular dependencies.
> remove warnings

- unified-codes/apps/web/src/components/containers/explorer/ExplorerTablePagination.tsx
Fixes #238 
Oh dear. Missed this when undoing other changes. Caused a typescript error.
> #238 typescript error due to removed classes

- unified-codes/apps/data-service/src/app/resolvers.ts
- unified-codes/apps/data-service/src/app/schema.ts
- unified-codes/apps/data-service/src/app/types/DgraphDataSource.ts
- unified-codes/apps/data-service/src/app/types/RxNavDataSource.ts
- unified-codes/libs/data/src/lib/types/Entity.ts
Fixes #252.
Branched off #251.
Migrates data source + resolver logic to data source classes.
> #252 add interactions default resolver

- README.md
- unified-codes/tools/scripts/dgraph/README.md
Fixes #285.
Super small PR to fix a few incorrect paths that were bothering me.
Also added some brief instructions on starting `data-service`, `web` and `storybook`
> #285 update main readme.md file

- unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts
- unified-codes/tools/scripts/dgraph/data/v2/schema.gql
Fixes #291.
Migrates v1 `entities` query to v2 backend.
> #291 migrate v1 entities query to v2 backend

- unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts
Fixes #296.
Map entity and product query from V1 Apollo Schema to V2 data source.  
> #296 migrate v1 entity resolvers to v2 backend

- unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts
- unified-codes/libs/data/src/lib/v1/Entity.ts
Fixes #302 
Query parent node to correctly return entity type in V1 API when using V2 Dgraph data.
Little bit untidy since it's grabbing more data than technically needed...but fixes the problem of incorrect data being returned?
> #302 consumables/other returned as drug

- unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts
Fixes #300.
Maps v1 types to v2 categories for compatibility with web frontend.
> Add mappings for v1 types to v2 categories

- unified-codes/apps/web/src/propertyFormats.ts
- unified-codes/release-uc.sh
- unified-codes/tools/scripts/dgraph/migration/v2/DataParser.ts
Fixes #320 
Change code from `code_eml` to `who_eml` and test.
> #320 error in eml properties

- unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts
Fixes #322.
Maps `product` entity property type values to the format specified by the graph schema.
> #322 add product entity graphql mapping

- unified-codes/tools/scripts/dgraph/data/v1/products.json
Fixes #323 .
Just ran a regex find-replace to stringify all the `code_rxnav` values (the inconsistency was annoying me).
> #323 update code_rxnav property values

- unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts
Fixes #324.
This hurt to write. Logic is simple enough: if query is coming from mSupply, just hand it back what we know it wants. Goes without saying that at some point this will need to be fixed properly, or risk the `data-service` resolver logic becoming horribly hacky and difficult to work with!
Not going to add any tests for this, but will probably be a good idea to when we get a proper fix working (which will probably involve some updates to mSupply).
> #324 dirty mSupply cludge fix

- unified-codes/apps/data-service/src/app/v1/schema.ts
- unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts
- unified-codes/apps/web/src/components/containers/explorer/ExplorerToggleBar.tsx
- unified-codes/apps/web/src/reducers/ExplorerReducer.ts
- unified-codes/apps/web/src/sagas/ExplorerSaga.ts
- unified-codes/apps/web/src/selectors/ExplorerSelectors.ts
- unified-codes/apps/web/src/types/Explorer.ts
- unified-codes/apps/web/src/types/Store.ts
- unified-codes/libs/data/src/lib/v1/Entity.ts
Fixes #347.
Untangles a bit of the category vs. type cludges. A bit clearer, but could still use a bit of clarification re. type mappings. Backend resolvers can only be fixed up so much, as need to retain support of existing mSupply query (until we can migrate everyone off it). 
> #347 web toggle category

- unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts
- unified-codes/libs/data/src/lib/v2/entity/Entity.ts
- unified-codes/libs/data/src/lib/v2/index.ts
Fixes #350.
Replaces some hardcoded strings with clearer constants.
> #350 add v2 entity constants

- unified-codes/apps/web/src/components/containers/detail/DetailEntityListItem.tsx
Fixes #376.
Fixed buggy conditional preventing child properties from rendering if no child entities existed.
> #376 fix missing child properties

- unified-codes/apps/web/src/components/containers/about/AboutContent.tsx
Fixes #64
Add minimal RxNav disclaimer to About page (meant to do before publishing oops).
> #64: Update AboutContent.tsx with RxNav disclaimer

- unified-codes/apps/web/src/components/containers/about/AboutPage.tsx
Fixes #389
- Add bottom padding to content container to push any content above the Footer (this feels a little hacky but does look better?)
> #389 Increase bottom padding on about page content

- unified-codes/apps/data-loader/src/app/v2/DataParser.ts
Fixes #392
As per title. #358 will reduce some of these errors I think!
> #392 Update DataParser.ts to account for uc5 to uc7

- unified-codes/apps/web/src/components/containers/app/AppHeader.tsx
- unified-codes/apps/web/src/components/containers/explorer/ExplorerPage.tsx
Fixes #397
- Hide avatar icon that doesn't do anything yet
- Swap cat spinner for material-ui spinner (😿  this hurts)
> #397 Professional-ise (ize?) the UI very slightly

- unified-codes/apps/web/src/components/containers/explorer/ExplorerPage.tsx
- unified-codes/apps/web/src/components/containers/explorer/ExplorerSearchBar.tsx
- unified-codes/apps/web/src/components/containers/explorer/ExplorerTable.tsx
- unified-codes/apps/web/src/selectors/ExplorerSelectors.ts
- unified-codes/libs/ui/.storybook/tsconfig.json
- unified-codes/libs/ui/src/lib/components/inputs/molecules/ClearInput.tsx
- unified-codes/libs/ui/src/lib/components/inputs/molecules/SearchBar.tsx
Fixes #396
Add some placeholder and helper text to the explorer UI
Went with @mark-prins  suggestion here: https://github.com/openmsupply/unified-codes/issues/396#issuecomment-846656707
I got a bit confused with where to put the props and helper text (also the placeholder text for a code search seems a bit redundant but the filter type is there so...just in case someone tries to use it I guess?)
> #396 add visual indication of wildcard

- unified-codes/apps/web/src/types/Detail.ts
- unified-codes/libs/data/src/lib/v1/Entity.ts
Fixes #411
Very minor addition of immediate packaging label (just because it looks pretty confusing without it)
> #411 Immediate packaging displayed as undefined

- unified-codes/apps/data-loader/src/app/v2/DataParser.ts
- unified-codes/apps/data-loader/src/app/v2/types/EntityNode.ts
Fixes #358 and #357
... Sorry I had to.
Was investigating/looking at #407 and it's just too tedious to troubleshoot missing codes/levels every time we need new ones 😿 
- Modularised node creation logic
- Modularised child linking logic
- Removed code generation from property nodes
> #358 Update data parser

- frontend/system/src/Entities/ListView.tsx
Fixes #463
Adds the `type: drug` filter so we get the same result as we used to!
> fix browse query

- frontend/system/src/Entities/EntityTreeItem.tsx
Fixes #508
Adds copy button to properties to allow easy copying of external codes:
> Copy properties

- frontend/host/src/components/AppBar/AppBar.tsx
> remove second link import

- frontend/host/src/Site.tsx
Fixes #483
Submitted a PR to fix the details page redirect last week but I redirected from /details instead of /detail 🙈
> fix the detail redirect

- frontend/host/src/components/AppDrawer/AppDrawer.tsx
- frontend/system/src/Admin/Configuration/OptionListConfigTab.tsx
- frontend/system/src/Entities/Barcodes/BarcodeEditModal.tsx
Fixes #577
Little UI changes (naming, order of elements...)
> 577 little cleanups
